#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Cyber Security Society - University of Wolverhampton
# Website language
lang: en-UK
# Header Title
header-title: Cyber <strong>Security</strong> Society
# Header Tagline
headter-tagline: Wolverhampton

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: cybersocwlv@gmail.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: 


#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyAOWnL8UQ4SrTsQx3hLR0NJjMvXsPHySJ4
map-text: University of Wolverhampton
map-text-location: Wolverhampton, West Midlands
map-lat: 52.588139
map-lng: -2.127338

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome
about-description: This is the website for the University of Wolverhamptons Cyber Security Society. Membership is beneficial to anyone studying a subject within the IT field, Management and Business students may also find keeping current on cyber security provides an advantage. Additionally, anyone with an interest in cyber security is encouraged to join.


#####################################
#############  What We Do  ############
#####################################
features-title: What We Do
features-description: In keeping with the aims of the society we regularly meet to share knowledge and support each others learning. We aim to provide opportunities to network, we create learning materials, organise trips, invite guest speakers and run events.

#
# Features
#
features:

# Feature
- title: Presentations & Events
  description: Throughout the year we run events and presentations designed to keep you up-to-date on cyber issues.
  icon: pe-7s-airplay

# Feature
- title: Learning & Support
  description: We are a group of students and staff who get together to share knowledge and support each others learning.
  icon: pe-7s-help2

# Feature
- title: Networking
  description: Through regular meetings, events and presentations, often with guest speakers you have the opportunity to network.
  icon: pe-7s-vector


#####################################
##########  Upcoming Events  ##########
#####################################
core-title: Upcoming Events
core-description: This section will contain upcoming events once they have been scheduled. Some of our events are open to non-students.


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Keep up-to-date with the latest society news. We also create articles on various cyber security subjects here.


#####################################
############### Team ################
#####################################
team-title: Meet The Team
team-description: Below are the members of the societys board.

#
# Team Members
#
team:

# Team Member
- name: Matt Skilton
  tagline: Chairperson
  avatar: avatar-01.jpg

# Team Member
- name: James Young
  tagline: Secretary
  avatar: avatar-02.jpg

# Team Member
- name: Mo Nassar
  tagline: Treasurer
  avatar: avatar-04.jpg

# Team Member
- name: Ecaterina Doe
  tagline: Communications Secretary
  avatar: avatar-03.jpg

# Team Member
- name: Ankit Mehrotra
  tagline: Postgraduate Secretary
  avatar: avatar-02.jpg
  
  # Team Member
- name:   Maria Ruan
  tagline: Undergraduate Secretary
  avatar: avatar-03.jpg


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: To join the society send us an email and we will get back to you sharpish! See individual email addresses above if you would like to contact a board member specifically.


#####################################
#############   Footer   ############
#####################################
footer-description: Wulfruna Street, Wolverhampton, WV1 1LY
footer-copyright-text: University of Wolverhampton Cyber Security Society
footer-copyright-year: 2018
